2018 valna hromada
zverinec/zverinec-docs pull request #5
Opened 2018-11-15 21:02 UTC by GiraffeReversed

2018-11-15 21:08 UTC, mukrop commented
Trochu by som preformuloval to hlasovanie na mieste ako "predbezne" alebo take nieco a doplnil info, ze valna hromada nebola uznasaniaschopna (a pocet clenov, ktori tam boli + pocet vsetkych).
Rovnako pri online hlasovani by som isiel s cislami, jasne napiast "XX za, 0 proti, 0 sa zdrazalo" (je to taky celkom dobry prehladny standard).
Potom to prosim daj skontrolovat este niekomu dalsiemu (asi staci ich oznacit tu v konverzacii a im pride notifikacia).

2018-11-16 08:02 UTC, Krejdom commented
Tu poznámku o "předběžném" rozhodnutí bych přidala i k výboru. A u výčtu přítomných bych před poslední závorku přidala čárku nebo "a".

2018-11-16 08:02 UTC, Krejdom commented
Tu poznámku o "předběžném" rozhodnutí bych přidala i k výboru. A u výčtu přítomných bych před poslední závorku přidala čárku nebo "a".

2018-11-16 21:47 UTC, malinajan requested changes

2018-11-16 21:47 UTC, horacekj commented on 2018-10-22_zapis.tex
> +\section*{Zápis z výroční schůze Spolku přátel severské zvěře}
Zápis z valné hromady Spolku přátel severské zvěře?

2018-11-16 21:47 UTC, horacekj commented on 2018-10-22_zapis.tex
> +\item O aktivní členství zažádali a byli přijati: Veronika Brugerová a Martin Kurečka.
Veronika Burgerová

2018-11-19 18:11 UTC, GiraffeReversed commented
#připomínkyZapracovány

2018-11-19 19:04 UTC, mukrop commented
Za mna v aktualnom stave OK (hoci som vahal, ci v hlasovani sa naozaj 25 ludi zdrzalo, ale nakoniec som usudil, ze ano, pretoze to bolo hlasovanie posielane vsetkym).
Prosim este jeden z @Krejdom @horacekj sa na to pozrite a ak to bude OK, zavrite pull request.

2018-11-24 20:12 UTC, horacekj commented
Dovolil jsem si přidat `prostredoskolaky.muni.cz`.

2018-11-24 20:12 UTC, malinajan approved these changes

2018-11-24 20:40 UTC, mukrop commented
OK, zatvaram, uz to preslo pripomienkovym konanim viac nez dost :-P.

2018-11-24 20:40 UTC, merged

2018-11-24 20:46 UTC, mukrop commented
Zapis je zverejneny na webe.