Valna_hromada_2019_zapis
zverinec/zverinec-docs pull request #6
Opened 2019-11-26 20:24 UTC by GiraffeReversed

2019-11-27 09:50 UTC, mukrop requested changes
Upravil by som:
* InterLoS 2019: Doplnil by som zmienku, ze organizacia pokracuje a ulohy postupne vymyslame a estujeme uz teraz.
* Aktivity, které hledají...: "propagace Spolku" -> "spoluprace spolku s propagacnim oddelenim FI MU"
* prostredoskolaky.muni.cz: doplnil by som, ze "maju uz aj jednotny prehlad vypisovanych SOC tem pre FI, PřF a ESF"
* V sekcii "Ostatni" vaham, ci nevypisovat plne mena (ale zase takto je to na druhu stranu prijemne neformalne).
* Rovno mozes pridat moje meno do ludi, ktori to skontrolovali.

2019-11-27 12:13 UTC, horacekj commented
Za mě ok.

2019-11-29 10:50 UTC, GiraffeReversed commented
Připomínky zohledněny.

2019-11-29 11:07 UTC, mukrop approved these changes

2019-11-29 11:07 UTC, mukrop commented
Prosim urob update aj na web.

2019-11-29 11:07 UTC, merged